[build]
  command = "php artisan config:cache && php artisan route:cache && php artisan view:cache"
  publish = "public"

[build.environment]
  PHP_VERSION = "8.2"

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200
